version: '3.8'

services:
  app:
    build:
      context: ./makedonskaBerza2
      dockerfile: Dockerfile
    image: snezekoleva/mse_spring:latest
    container_name: mse_spring
    ports:
      - "80:9090"
    environment:
      SPRING_APPLICATION_JSON: '{"techanalysis.baseurl":"http://analysis:5000"}'
    depends_on:
      - analysis
    networks:
      - mse-network

  analysis:
    build:
      context: ./Python Scripts/analysis
      dockerfile: Dockerfile
    image: snezekoleva/mse_analysis:latest
    container_name: mse_analysis
    ports:
      - "5000:5000"
    environment:
        - DATABASE_URL:"postgresql+psycopg2://mse_owner:CYXP4fDEiH5g@ep-bold-dream-a2fi281z.eu-central-1.aws.neon.tech:5432/mse?sslmode=require&options=endpoint%3Dep-bold-dream-a2fi281z"
    networks:
      - mse-network

  jobs:
    build:
      context: ./Python Scripts/mse_scraper
      dockerfile: Dockerfile
    image: snezekoleva/mse_scraper:latest
    container_name: mse_scraper
    ports:
      - "6000:6000"
    networks:
      - mse-network


networks:
  mse-network:
    driver: bridge
